### ISSUE TITLE
uninitialized constant Rails::Railtie (NameError)

### ISSUE THREAD

**Issue by ghazel** [validates-email-format-of/validates_email_format_of#53]
```
/Library/Ruby/Gems/2.0.0/gems/validates_email_format_of-1.6.2/lib/validates_email_format_of/railtie.rb:2:in `<module:ValidatesEmailFormatOf>': uninitialized constant Rails::Railtie (NameError)
    from /Library/Ruby/Gems/2.0.0/gems/validates_email_format_of-1.6.2/lib/validates_email_format_of/railtie.rb:1:in `<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/validates_email_format_of-1.6.2/lib/validates_email_format_of.rb:150:in `<top (required)>'
```

**Comment by alexdunae** [comment]
All our tests are passing at the moment so I'm going to assume this got fixed at some point in the past seven years.  Feel free to re-submit an issue if not.
